apiVersion: 1

datasources:
  - name: nuDemo PostgreSQL
    uid: nudemo-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: nuscenes
    user: nuscenes
    isDefault: false
    editable: false
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: nuscenes
